# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master

    border_size = 2
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# Make browser slightly more transparent
# (handled by default config: ~/.local/share/omarchy/default/hypr/apps/browser.conf)

# Vicinae settings - https://docs.vicinae.com/quickstart/hyprland
layerrule = blur on, match:namespace vicinae
layerrule = ignore_alpha 0, match:namespace vicinae
layerrule = no_anim on, match:namespace vicinae

workspace = special:scratchpad, gapsout:75, gapsin:25
